spring:
  profile:
    active: ${PROFILE}
  application:
    name: Students

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  liquibase:
    enabled: true
    change-log: "db/changelog/db.changelog-master.xml"

server:
  port: ${SERVER_PORT}

debug: false

logging:
  level:
     liquibase: INFO

